services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python3 app.py
    restart: always
    container_name: bd-teste-conexao
